import pandas as pd

def InitialiseData(file):
    df = pd.read_csv(file)
    df.columns = df.columns.str.strip().str.replace('"', '', regex=False)

    # Rename columns for simplicity. 
    # Note: Can check if the file has already undergone this change to increase speed.
    df = df.rename(columns={
        "1. Date & Start time": "Start Date",
        "2. End time (inc. travel time)": "End Date",
        "Callout time (autogenerated)": "Callout Time",
        "3. Callout type": "Callout Type",
        "4. Suburb": "Suburb",
        "5. Street address/Long/lat coordinates": "Street Address",
        "6. Called by (WV, WR, etc": "Called By",
        "7. Case No (WV# etc)": "Case No",
        "8. Attended by": "Attended By",
        "9. Issue": "Issue",
        "10. Animal type": "Animal Type",
        "11. Species (optional)": "Species",
        "12. # of animals": "No of Animals",
        "13. Notes (treatment & outcome details)": "Notes",
        "14. Outcome": "Outcome",
        "15. Entered by": "Entered By",
        "16. Darter/s": "Darter/s",
        "17. Approving vet": "Approving Vet",
        "18. Dart drugs/meds used": "Drugs/Meds Used",
        "19. Total # of Darts Used": "Total No of Darts",
        "20. WV callout being invoiced": "WV Callout Invoiced",
        "21. Photo ok to post": "Photo Post Status",
        "22. Files & media (photos/vids)": "Files & Media",
        "Post Monitoring Address/Coordinates": "Post Monitoring Address",
        "Closest Roo Reserve it came from?": "Closest Too Reserve",
    })
    return df


# Check for blank job code && decision to delete
def BlankJobCode(df): # for some reason df is not a necessary input
    blankJobCodes = []
    for index, value in df["Job Code"].items():
        if pd.isnull(value):
            blankJobCodes.append(index)

            # Null status of other values:
            startDate = df.loc[index, "Start Date"]
            endDate = df.loc[index, "End Date"]
            calloutType = df.loc[index, "Callout Type"]
            street = df.loc[index, "Street Address"]
            suburb = df.loc[index, "Suburb"]

            # Scenario (for delete decision) #1
            if pd.isnull(startDate) and pd.isnull(endDate) and pd.isnull(calloutType) and pd.isnull(street) and pd.isnull(suburb):
                df.drop(index, inplace=True)

    return blankJobCodes

# Returns dictionary of columns with blanks (+ the index of the blank)
def BlanksOtherFields(df):
    emptyValues = {}
    cols = ["Start Date", "End Date", "Callout Time", "Callout Type", "Suburb", "Street Address", "Called By", "Attended By", "Issue", "Animal Type", "Species", "No of Animals", "Outcome", "Entered By"]

    for col in cols:
        if df[col].isnull().any():
            for index, value in df[col].items():
                jobCode = df.loc[index, "Job Code"]
                if pd.isnull(value) and pd.isnull(jobCode) == False:
                    emptyValues.setdefault(col, jobCode)
    return emptyValues

# need to check if Total # of Darts is empty if Darter is listed!
def DartCheck(df):
    emptyDarts = []
    for index, value in df["Darter/s"].items():
        if pd.notnull(value):
            if pd.isnull(df.loc[index, "Total No of Darts"]) and pd.notnull(df.loc[index, "Job Code"]):
                emptyDarts.append(df.loc[index, "Job Code"])
    return emptyDarts